### PR TITLE
PHP8 support

### PR DESCRIPTION
**Pull request by afk11**
Hi

This PR adds support for PHP8.0. I tried against a couple of PHP versions, tests run on 7.3, 7.4, 8.0. I don't think this PR removes support for any old versions.. but to test on older versions I'd have to make more changes to composer.lock.

Could you merge and release when you get a chance?

Happy new year!

### CODE REVIEW

**Comment by b1rdex** [comment]
`composer.lock` file should be removed. It doesn't do much in libraries.

**Comment by afk11** [comment]
@b1rdex Agreed, I left it in the repo because it was there before me..

**Comment by abgit** [comment]
Can someone merge this?
Otherwise all projects that use this lib are stuck on php7.

**Comment by BafS** [comment]
@lastguest would you be able to merge this PR please ? It's a blocker when we use this library with PHP 8. Otherwise we will have to fork it.

**Comment by abgit** [comment]
new tag too?

**Pull request merged**
